### ISSUE TITLE
autograde setup

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#1]
hey @kdcurry @jlpalomino i've setup the autograde package here. it occurred to me that the other repo with the EA specific course grading elements may need to be a package now. this could break things. please let me know how installing goes and whether we should setup the course specific package as a in earth-analytics-python so that too can be imported locally.

**Comment by lwasser** [comment]
@kdcurry and @jlpalomino  i was able to import this. I suspect we will want to create ANOTHER private package for grading that is specific to each course. let's work through this together online tomorrow. i did NOT set that up yet but can tomorrow or this evening depending!

**Comment by kdcurry** [comment]
@lwasser I agree we need to do something with the EA specific course grading elements. I think a private package will work. Let me know if you set this up!

EDIT: I am also thinking this folder can live in the folder with the homework assignments within the earth analytics python repo if we don't want to make another package?

**Comment by lwasser** [comment]
it should be setup @kdcurry i created a subpackage called earthanalytics here: 
https://github.com/earthlab/earth-analytics-python/tree/master/ea-class-autograde

And added instructionst o install it here:

https://github.com/earthlab/earth-analytics-python/blob/master/README.md

can you please try to install and use it? i was able to install it last night but i didn't try to actually use anything in it i just imported `earthanalytics` and it seemed to work.

**Comment by lwasser** [comment]
so when you've tried to install and use both packages - autograde and earthanalytics and they work please report back here. let me know what works and what doesn't work please! i'm going to assign this task to you to work on. i can help fix things again on thursday.

**Comment by kdcurry** [comment]
Perfect! Enjoy the mountain @lwasser

**Comment by kdcurry** [comment]
Both packages have been installed and everything seems to be working! Nice work @lwasser

**Comment by lwasser** [comment]
oh great!! that is actually amazing that it just worked first time @kdcurry  thank you for testing it for me!! Are all of the functions working as you suspect they should in the packages too?

**Comment by lwasser** [comment]
the mountain was great. no wind and NO ONE was on the summit :) it was amazing!

**Comment by kdcurry** [comment]
Seems like everything is working as expected!

**Comment by lwasser** [comment]
also closing this as we've moved away from the second pakage altho it is still available if we needed it. using nbgrader now.
