### ISSUE TITLE
Add custom error messages to assertion functions in base module

### ISSUE THREAD

**Issue by marty-larocque** [earthlab/matplotcheck#106]
Some of the assertion functions in the base module have optional custom error messages, but most do not. We would like to let all of the functions in the base module have custom error messages.

**Comment by lwasser** [comment]
great -- this is a great first issue @ryla5068 ... so are you proposing to add the ability to provide custom messages for each assert method? that is all that is missing in this issue. i'm going to label this as an enhancement and will assign it to you.

**Comment by lwasser** [comment]
@ryla5068 can you please add this issue to the changelog?

https://github.com/earthlab/matplotcheck/issues/106
