### ISSUE TITLE
Move contributing setup content from readme

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#121]
Currently the readme file has some contributing info at the bottom. it should all live in the CONTRIBUTING.rst file (i think it's there). let's remove that info from the readme

**Comment by lwasser** [comment]
@nkorinek  this is a small easy task.

1. make sure the contributing info in the screenshot below is in the docs rather than the readme. i think that is how we did it in earthpy. can you

<img width="955" alt="Screen Shot 2020-03-06 at 3 51 03 PM" src="https://user-images.githubusercontent.com/7649194/76128727-51451f00-5fc2-11ea-99da-cce3d5c607b2.png">

2. add your name as an active contributor!
3. can you change both your name and mine to github images like i have the other contributors in the readme please?
4. make sure your name is in the [zenodo file](https://github.com/earthlab/matplotcheck/blob/master/.zenodo.json)

so you can get credit for your effort here!!

**Comment by nkorinek** [comment]
https://github.com/earthlab/matplotcheck/pull/213 fixed here, can be closed! @lwasser

**Comment by lwasser** [comment]
wonderful!! closing
