### ISSUE TITLE
Write Tests for Line Tests in Base Module

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#131]
It looks like there is no coverage for those asserts currently

https://codecov.io/gh/earthlab/matplotcheck/src/master/matplotcheck/base.py 

The lessons where the line tests are used are here:

* https://www.earthdatascience.org/courses/earth-analytics-python/lidar-remote-sensing-uncertainty/

* https://github.com/earthlab/earth-analytics-lessons/tree/master/courses/earth-analytics-python/05-raster-vector-extract-data

If you write the tests for these plots, please add the notebook here:
https://github.com/earthlab/earth-analytics-lessons/tree/master/1-additional-content under `ea-python-assignments`

**Comment by lwasser** [comment]
this is being addressed in pr #239

**Comment by nkorinek** [comment]
This can be closed, fixed in #274 @lwasser

**Comment by lwasser** [comment]
wow it feels good to close issues!! thank you again!
