### ISSUE TITLE
Change documentation or return type for assert functions

### ISSUE THREAD

**Issue by marty-larocque** [earthlab/matplotcheck#148]
Currently, assertions which may raise an error but return nothing are documented like this in the base module:
```
Returns
-------
None :
    Nothing if plot contains the expected number of bins, otherwise throws AssertionError.
```
However, there is built-in functionality in Sphinx for raises. Therefore, assertions should be documented like this:
```
Raises
------
AssertionError
    if the heights of histogram bins do not match `bin_heights`
```

**Comment by lwasser** [comment]
this has been completed!
