### ISSUE TITLE
Add absolute tolerance functionality to assert_xydata() and assert_bin_heights()

### ISSUE THREAD

**Issue by marty-larocque** [earthlab/matplotcheck#157]
Currently, `assert_xydata()` and `assert_bin_heights()` support relative tolerance but not absolute tolerance. Absolute tolerance should be implemented in these functions. This should be a trivial change given how tolerance is currently implemented with `np.testing.assert_allclose()`.

**Comment by lwasser** [comment]
hey @ryla5068 can you double check that this is addressing tolerance for both histograms and other types of plots? if it does - cool! if it doesn't just note what we DIDN't address here!

**Comment by marty-larocque** [comment]
@lwasser this can be closed when #234 is merged. As we decided previously, we are removing relative tolerance functionality and adding absolute tolerance in its place (as opposed to in addition). 

This PR also addresses tolerance for histograms.
