### ISSUE TITLE
Add range option to histogram test in raster module

### ISSUE THREAD

**Issue by nkorinek** [earthlab/matplotcheck#164]
Currently, a histogram of a raster being tested has to have an exact amount of bins and an exact range of values to pass the test in the raster module. We might want to consider adding a more dynamic test that can accept a range of bin values so there is some flexibility for students.

**Comment by lwasser** [comment]
@nkorinek when you say dynamic - can you clarify what you mean? do you mean a range of bins like hist has between 5 and 10 bins? rather than a specific number? the word dynamic is throwing me off!!

**Comment by nkorinek** [comment]
@lwasser yep that's exactly what I had envisioned! I pictured it taking a range, or possibly just a list with the upper and lower limits (i.e., `range = [5, 10]`) and checking the number of bins assigned was in between those values.

**Comment by nkorinek** [comment]
With the addition of the `assert_bin_midpoints()` function to the raster module, I don't really think this is a feasible addition anymore. We can't account for these ranges in other tests that we do. We don't really allow for much flexibility in what the plotted data should look like elsewhere in the package, so I don't see why we would here. Maybe we should just close this issue, unless you think there's still a solution for this? @lwasser
