### ISSUE TITLE
Vector Module: Check points should work like lines and polys

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#176]
I currently don't see a good way to check xy point data ... i can use assert_xy but that data need to be manipulated for this to work prooperly. Ideally we'd have a assert_points in the vector testor that worked like lines and polys and accepted a GDF that could be used to test for the correct data.  

i'll post more on this but homework 3 in ea python 2020 has perfect examples of where this would be used.

**Comment by nkorinek** [comment]
I'm going to start looking into this!

**Comment by nkorinek** [comment]
pr here: https://github.com/earthlab/matplotcheck/pull/203

**Comment by lwasser** [comment]
this was completed via #203 closing
