### ISSUE TITLE
Histogram functionality - Get Bin Midpoints Functionality

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#184]
Currently you can access the values of a histogram which i believe represents bin height. Bin height is actually the number of observations that utilize that bin. But we also want to grab the value of the bin itself so for instance 0-1 has 10 observations. 10 is the height. but we should be able to get atleast a middle point value for the bin range itself. 

We probably should rethink the names of some of these methods so they are more specific to what they actually do.

**Comment by nkorinek** [comment]
Working on this!

**Comment by nkorinek** [comment]
pr: https://github.com/earthlab/matplotcheck/pull/204

**Comment by nkorinek** [comment]
merged, this can be closed @lwasser !

**Comment by nkorinek** [comment]
just a reminder that this can be closed @lwasser

**Comment by lwasser** [comment]
closing!!
