### ISSUE TITLE
examples for a few classes

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#2]
hey @kdcurry it would be really great to have a bit of documentation embedded in some of the classes. If you have a bit of time this week (i know it is tight!) can you kindly have a look at other packages like: https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/brief.py and take not of how they have examples of how things would be called within the classes / methods / functions. please let me know if this doesn't make sense. a few of these would be very nice.

**Comment by lwasser** [comment]
just making sure you see this too @kdcurry  ...

**Comment by kdcurry** [comment]
yup, I'll get it done by tomorrow! @lwasser

**Comment by lwasser** [comment]
closing as we have autodoc setup on docstrings. and we can create more specific issues for examples added to the docstrings as need be.
