### ISSUE TITLE
Create a vignette for testing vector plots

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#208]

**Comment by nkorinek** [comment]
@lwasser I could start tackling this too!

**Comment by lwasser** [comment]
@nkorinek that would be awesome!! thank you

**Comment by nkorinek** [comment]
@lwasser this can be closed, was merged here! https://github.com/earthlab/matplotcheck/pull/220

**Comment by nkorinek** [comment]
@lwasser reminder that this can be closed!

**Comment by lwasser** [comment]
Thank you @nkorinek closing!!
