### ISSUE TITLE
Change to line_types parameter of base.assert_lines_of_type()

### ISSUE THREAD

**Issue by marty-larocque** [earthlab/matplotcheck#237]
Currently, `base.assert_lines_of_type()` only accepts a list of strings for the `line_types` parameter.

It would be simple and convenient to change it to also accept a single string.  This would be useful if only one type of line needs to be checked for.

**Comment by marty-larocque** [comment]
@lwasser this can be closed when #239 is merged.

**Comment by nkorinek** [comment]
This can be closed, fixed in #274 @lwasser

**Comment by lwasser** [comment]
closing!
