### ISSUE TITLE
ValueError when calling assert_lines_of_type() with line_types='regression'

### ISSUE THREAD

**Issue by marty-larocque** [earthlab/matplotcheck#238]
If `base.assert_lines_of_type()` is called with `line_types='regression'` on a plot without a regression line, we would expect it to raise an `AssertionError`.

However, if we do this on a plot with only a one-to-one line, `base.assert_lines_of_type()` will raise a `ValueError`. This is because the method for determining if a regression line exist uses the xy-data for each line. One-to-one lines do not necessarily have specific xy-data.

We should rewrite this function to account for this case.

**Comment by lwasser** [comment]
can you please provide some example code that highlights this issue ?

**Comment by marty-larocque** [comment]
Here is a gist demonstrating this issue.
https://gist.github.com/ryla5068/0f404cc9a5fae4fb5981aa21dd473672

**Comment by lwasser** [comment]
@ryla5068 can you clarify what is going on with this issue?? if we can close it please let me know.

**Comment by marty-larocque** [comment]
@lwasser the description for this issue is a bit misleading. This was caused by a weird way were were checking the line. This is addressed in #239, and can be closed when that PR is merged.

**Comment by nkorinek** [comment]
This can be closed, fixed in #274 @lwasser

**Comment by lwasser** [comment]
closing!!
