### ISSUE TITLE
Remove m2r as dependency

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#246]
1. change code_of_conduct to .rst
2. remove mr2 in the deps

https://github.com/earthlab/matplotcheck/blob/master/dev-requirements.txt#L5

**Comment by lwasser** [comment]
@nkorinek can you add the PR where this was addressed so i can close this issue? i'm trying to close issues that have been addressed!!

**Comment by nkorinek** [comment]
https://github.com/earthlab/matplotcheck/pull/247 pr here!

**Comment by lwasser** [comment]
thank you !! closing!!
