### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#3]
Currently - when you install autograde is relies on the earth-analytics-ptyhon envt. probably better to just specify all of the depnedencies in the package!

**Comment by kdcurry** [comment]
Some of these packages may already be embedded in Python:
numpy, pandas, geopandas, matplotlib, shapely, folium

I think these come with Python. If not, they will need to be added to the dependencies:
dateutil, math, scipy

**Comment by lwasser** [comment]
ok closing this issue as i believe we have a solid testing envt setup now.
