### ISSUE TITLE
pytest warning: Too many plots opened

### ISSUE THREAD

**Issue by kysolvik** [earthlab/matplotcheck#52]
When I run pytest, matplotlib raises a warning about the number of plots that have been opened. I'm guessing each time a plot fixture is used, a new plot is opened. It doesn't ever render them and still seems to run fast, but maybe we should explicitly close them at the end of each test function? 

Here's the warning:
"RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`)."

**Comment by lwasser** [comment]
hey @kysolvik totally. you just need to ensure you close each plot

https://github.com/earthlab/earthpy/blob/master/earthpy/tests/test_plot_bands.py#L20

i can't remember if ive done this with fixtures but i would imaging it would work the same where you call the fixture and then close it at the end of the text explicitly! We had the same issue with earthpy.

**Comment by kysolvik** [comment]
awesome, I'll give it a shot. Thanks @lwasser!

**Comment by lwasser** [comment]
closing this as i fixed it in #56 referenced above!!
