### ISSUE TITLE
Matplotcheck -- title_contains bug

### ISSUE THREAD

**Issue by lwasser** [earthlab/matplotcheck#84]
This code creates a custom error code associated with words not found in a title.
for will - it is writing out the word that is NOT in the list, not the word that is missing from the plot or expected to be in the title.   

```
for s in lst:
                assert (
                    s.lower().replace(" ", "") in title
                ), "Title does not contain expected text:{0}".format(s)
```

**Comment by lwasser** [comment]
@nkorinek this as well. we've done so much work on this method it may work now but this is another thing for you to look into!  i do'nt want to add to many things at once but if you start working on it i'll add your name to it.

**Comment by nkorinek** [comment]
@lwasser hey! So I'm not sure quite what this issue is saying the problem is. What words should the error be throwing that it's not throwing? Thanks, sorry for the confusion.

**Comment by lwasser** [comment]
@nkorinek if i remember correctly, the method writes out a message that says somethign like... let's pretend we want `dog` in the title. 
So if dog is not in the title it should say
oops - missing the word dog in the title (i think)? i recall it providing the other words that are in the title not the word dog. so if the title should include the word NAIP we want the message to tell them NAIP is missing from the title. 

Does that make sense? it may work correctly now. can you please let me know. this is an older issue for sure.

**Comment by nkorinek** [comment]
Just ran it on a test title that was "Test Title" with the `expected_title` equal to `["hi"]` and it threw the error `AssertionError: Title does not contain expected string: hi` so...I think this is fixed than, correct @lwasser ?

**Comment by lwasser** [comment]
it must be!! i'll close this issue then @nkorinek . thank you for looking into it!!
